name: kwic
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  file_picker: ^6.1.1
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.4.9
  freezed: ^2.4.5
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  logger: ^2.0.2+1
  oktoast: ^3.4.0
  orm: ^3.4.5
  path_provider: ^2.1.1
  riverpod_annotation: ^2.3.3
  window_manager: ^0.3.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  json_serializable: ^6.7.1
  build_runner: ^2.4.7
  custom_lint: ^0.5.7
  riverpod_lint: ^2.3.7
  riverpod_generator: ^2.3.9
  test: ^1.24.9

flutter:
  uses-material-design: true
